title: David Benoit # your name (or website title) here
logo: "/images/Linkedin_image.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Research Scientist with 8+ years of experience in analytics, multivariate statistics, and project design and implementation. Possess a PhD in Ecology and Evolutionary Biology from the University of Toronto.
  <br><br>
  Currently working with the Great Lakes Fishery Commission to develop a trait database for fishes of the Great Lakes and create clusters of species to facilitate selective passage at fishways. 
  <br><br>
  <a href="https://www.linkedin.com/in/dmbenoit">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
